### ISSUE TITLE
Adjust READMEs and Apply Fixes for Demos Base Images

### ISSUE THREAD

**Issue by eholum** [space-ros/docker#161]
We need to update a handful of references in the README and demo build files to handle folder moves and other changes from https://github.com/space-ros/space-ros/issues/177, including those pushed in https://github.com/space-ros/space-ros/pull/170.

There are still a few hard coded `~/spaceros` lying around, and we standardized some env variables (`ROS_DISTRO` instead of `ROSDISTRO`).

**Comment by martincerven** [comment]
Bump, wanted to try docker images as part of **NASA Space ROS Sim Summer Sprint Challenge**, only to find out you refactored a LOT just weeks ago and repo is currently in broken state, but looks like https://github.com/space-ros/docker/pull/162 fixes these ENV mismatches.

**Comment by eholum** [comment]
@martincerven Yep, sorry about that. The timing of taking on some significant reworking of our packaging + the challenge could definitely have been better.

If you want to move forward with either the latest release or the fix on main you can follow the instructions in https://github.com/space-ros/docker/issues/160#issuecomment-2282840466.
