### ISSUE TITLE
Simulation resources are not available for the Nav2 Demo

### ISSUE THREAD

**Issue by eholum** [space-ros/docker#201]
### Version or commit hash

main

### RMW Implementation

FastRTPS

### Steps to reproduce issue

Run the nav2 demo, the robot model does not appear in the rviz widget because the meshes are not available in the container. This I believe is an old issue unrelated to the recent change, just noticed it while testing.

### Expected behavior

Would like to see the rover for visualization purposes.

### Actual behavior

We only get tf and a geometry error saying the mesh files cannot be found.

<img width="621" alt="image" src="https://github.com/user-attachments/assets/53861de0-c1b2-4bc2-ab4d-86892e75ff41">

### Backtrace or Console output

e.g.

```
[rviz2-1] [ERROR] [1729629168.366980218] [rviz2]: Could not load resource [package://simulation/models/curiosity_
path/meshes/suspension_arm_F_L_fixed.dae]: Unable to open file "package://simulation/models/curiosity_path/meshes/suspension_arm_F_L_fixed.dae".                                                                                  
[rviz2-1] [ERROR] [1729629168.371587640] [rviz2]: Could not load resource [package://simulation/models/curiosity_path/meshes/suspension_arm_F_L_fixed.dae]: Unable to open file "package://simulation/models/curiosity_path/meshes
/suspension_arm_F_L_fixed.dae".    
```

**Comment by franklinselva** [comment]
I didn't realise there is a `nav2` demo. I am expecting the same case for `moveit2` too.

Do you think these demos can be adapter after space-ros/demos#31

**Comment by eholum** [comment]
Not gonna worry about this now, since we'll have time to rework that demo before the next release.
