### ISSUE TITLE
Docker Login resource required?

### ISSUE THREAD

**Issue by Pedro-Roque** [space-ros/docker#32]
Terminal output:
```
➜  demo_spaceros git:(main) ./build.sh 

##### Building Space ROS Demo Docker Image #####

Sending build context to Docker daemon  13.82kB
Step 1/31 : FROM openrobotics/spaceros:latest
pull access denied for openrobotics/spaceros, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

##### Done! #####
```
How can one request access to these repos?

**Comment by Ronoman** [comment]
The missing `openrobotics/spaceros` docker image can be built by following the README in the spaceros subdirectory in this repository: https://github.com/space-ros/docker/blob/main/spaceros/README.md.

**Comment by Pedro-Roque** [comment]
Thanks @Ronoman , fixed by building the spaceros Docker first. Also faced an issue related with GPU availability on docker, which required me to install the nvidia-container-toolkit. Maybe good to add this to the intructions as well, just in case / to a FAQ section
