### ISSUE TITLE
Vision_msgs not present when building space_robots image causing it to fail

### ISSUE THREAD

**Issue by j-corvo** [space-ros/docker#87]
Hello,

I was trying to build the space_robots image after I successfully built `moveit` and `spaceros` images, but I found the following error in the building process:

![Screenshot from 2023-11-20 01-00-51](https://github.com/space-ros/docker/assets/52609366/8fd28713-1c5c-4bb3-8139-aec86c483ded)

Am I missing any steps prior to this one? Or should we add `vision_msgs` repo to the `demo_manual_pkgs.repos`?

**Comment by EzraBrooks** [comment]
Interesting.. I have another project that uses Gazebo that doesn't require explicitly pulling in `vision_msgs`, and this was building fine until very recently. I wonder if there was a breaking change?

**Comment by KatherineZT** [comment]
I fixed this issue by adding the following repo in the `demo_manual_pkgs.repos` file of the `space_robots` directory :
```
vision_msgs:
  type: git
  url: https://github.com/ros-perception/vision_msgs.git
  version: ros2
```

**Comment by EzraBrooks** [comment]
I just noticed that the scheduled builds on this repo haven't been running due to inactivity - I'll run one to see if we encounter this issue in CI. Could one of you @KatherineZT @j-corvo open a PR with this addition?

Please use a tagged version, not `version: ros2`, thanks!

**Comment by EzraBrooks** [comment]
Confirmed that it is broken on main in CI as well: https://github.com/space-ros/docker/actions/runs/7214030223/job/19655225694
