### ISSUE TITLE
Earthly should ref-spec match Space ROS repos during build

### ISSUE THREAD

**Issue by Bckempa** [space-ros/docker#91]
To allow testing of cross-repo changes, the build infrastructure should support matching all space ROS repositories to the current ref-spec (branch or tag) if it exists.

For example, if making a chance on both the space-ros and docker repositories that must be tested together, setting the docker branch to `feature/foo` should also use the `feature/foo` branch of space-ros if it exists.

**Comment by yuyuqq** [comment]
I was able to build the docker image. Thank you!
